Algoritmo "Exercicio_5"

var
m, km, hm, dam, dm, cm, mm:real
inicio
   
   escreval("Digite uma distância em metros:")
   leia(m)

   km <- m / 1000
   hm <- m / 100
   dam <- m / 10
   dm <- m * 10
   cm <- m * 100
   mm <- m * 1000
   
   escreval("Em km:", km)
   escreval("Em hm:", hm)
   escreval("Em dam:", dam)
   escreval("Em dm:", dm)
   escreval("Em cm:", cm)
   escreval("Em mm:", mm)

Fimalgoritmo