Algoritmo "Exercicio_3"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//Seção de declarações
var
nome:caractere
salario:real

inicio
   //seção de comandos
   
   escreval("Digite o nome do funcionário?")
   leia(nome)
   
   escreval("Agora digite o salário deste funcionário")
   leia(salario)
   
   escreval("Nome do Funcionário: ", nome)
   escreval("Salário recebido: ", salario)

Fimalgoritmo